// 拡充カードデータ — description / skillName / skillEffect / nano-banana-pro プロンプト用
const CARD_DATA_FULL = [
  {
    id: 1, name: 'スライムくん', rarity: 1, type: 'モンスター', emoji: '🟢',
    description: 'のんびり屋さんだけど、意外と根性がある緑のスライム。',
    skillName: 'ぷにぷにアタック',
    skillEffect: '相手に小ダメージを与え、1ターン動けなくする。',
    promptTrait: 'a cheerful round green slime with big innocent eyes, sitting and smiling',
    promptTheme: 'nature green and lime green tones, forest themed border',
  },
  {
    id: 2, name: 'コボルド', rarity: 1, type: 'モンスター', emoji: '👹',
    description: 'ちょっと臆病だけど、仲間思いのリザードもどき。',
    skillName: 'ひっかきキズ',
    skillEffect: '相手に小ダメージ。確率でひるませる。',
    promptTrait: 'a small reptilian kobold creature with big scared eyes and tiny claws',
    promptTheme: 'earth brown and muddy orange tones, cave dungeon themed border',
  },
  {
    id: 3, name: '見習い剣士', rarity: 1, type: '冒険者', emoji: '⚔️',
    description: '夢は一流の騎士！まだまだ修行中の少年剣士。',
    skillName: '練習斬り',
    skillEffect: '相手に小ダメージ。成功するとATKアップ。',
    promptTrait: 'a young boy apprentice knight with an oversized sword, determined expression, simple armor',
    promptTheme: 'silver and sky blue tones, guild hall themed border',
  },
  {
    id: 4, name: '村の釣り師', rarity: 1, type: '冒険者', emoji: '🎣',
    description: '川べりで毎日竿を振る、のんびり村人。実は幻の魚を狙っている。',
    skillName: 'ちゃぽんと一投',
    skillEffect: '水属性の小ダメージ。たまに大物を引いて追加攻撃。',
    promptTrait: 'a relaxed old fisherman with a straw hat and fishing rod, sitting by a river',
    promptTheme: 'ocean blue and warm sandy tones, riverside village themed border',
  },
  {
    id: 5, name: 'たいまつコウモリ', rarity: 1, type: 'モンスター', emoji: '🦇',
    description: '洞窟の天井にぶら下がる、ちいさくて明るいコウモリ。炎が好き。',
    skillName: '火の粉ばら撒き',
    skillEffect: '全体に微小ダメージ。',
    promptTrait: 'a cute tiny bat carrying a small torch, with glowing orange eyes and wings spread',
    promptTheme: 'fiery orange and dark navy tones, dark cave with torchlight themed border',
  },
  {
    id: 6, name: 'キノコ戦士', rarity: 1, type: 'モンスター', emoji: '🍄',
    description: '森で生まれたキノコ人間。胞子をばら撒くのが得意。',
    skillName: '胞子ふきつけ',
    skillEffect: '相手をスリープ状態にする可能性がある。',
    promptTrait: 'a cute round mushroom creature warrior with a cap helmet and little legs, determined face',
    promptTheme: 'earthy red and mossy green tones, enchanted forest themed border',
  },
  {
    id: 7, name: 'アーチャー', rarity: 2, type: '冒険者', emoji: '🏹',
    description: '百発百中が自慢の弓使い。山育ちで動物語がわかるらしい。',
    skillName: '鷹の目射ち',
    skillEffect: '単体に中ダメージ。弱点に当たると追加ダメージ。',
    promptTrait: 'a nimble elf-like archer with a longbow, pointed ears and forest camouflage outfit, confident smile',
    promptTheme: 'emerald green and golden yellow tones, ancient forest themed border',
  },
  {
    id: 8, name: 'シーフ', rarity: 2, type: '冒険者', emoji: '🗡️',
    description: '影から現れ影に消える、謎多きスリの名人。',
    skillName: '影走り',
    skillEffect: '回避率アップ＆次ターン先制攻撃。',
    promptTrait: 'a sleek cat-like thief in dark hooded cloak with a mischievous grin and twin daggers',
    promptTheme: 'deep purple and silver tones, moonlit city rooftop themed border',
  },
  {
    id: 9, name: 'ゴブリンリーダー', rarity: 2, type: 'モンスター', emoji: '👺',
    description: 'ゴブリン軍団のボス。小さくてうるさいが統率力はある。',
    skillName: '号令ラッシュ',
    skillEffect: '2〜3回の連続攻撃。',
    promptTrait: 'a bossy goblin chieftain wearing a crown made of junk, pointing a stubby sword dramatically',
    promptTheme: 'murky yellow-green and rust red tones, goblin camp bonfire themed border',
  },
  {
    id: 10, name: 'ストーンゴーレム', rarity: 2, type: 'モンスター', emoji: '🗿',
    description: '遺跡の番人。命令がなければ何百年でも眠って待てる。',
    skillName: '岩盤パンチ',
    skillEffect: '単体に中ダメージ＋防御力ダウン。',
    promptTrait: 'a big chunky stone golem guardian with ancient rune carvings, slow and heavy posture',
    promptTheme: 'grey stone and mossy teal tones, ancient ruin themed border',
  },
  {
    id: 11, name: '森の魔女', rarity: 2, type: '冒険者', emoji: '🧙‍♀️',
    description: '森の奥に住む不思議なおばあさん魔女。薬の知識はピカイチ。',
    skillName: '毒りんごのスープ',
    skillEffect: '中毒ダメージを与え続ける。',
    promptTrait: 'a quirky old witch with a pointed hat, kind wrinkled face and a bubbling cauldron',
    promptTheme: 'dark teal and magical purple tones, moonlit forest clearing themed border',
  },
  {
    id: 12, name: 'ナイト', rarity: 3, type: '冒険者', emoji: '🛡️',
    description: '鉄壁の守りが自慢のベテラン騎士。傷だらけでも仲間を守る。',
    skillName: '鉄壁の守護',
    skillEffect: '全体の防御力を1ターンアップ。攻撃も跳ね返す。',
    promptTrait: 'a sturdy armored knight with a great shield, battle-worn armor and loyal eyes',
    promptTheme: 'royal blue and polished silver tones, castle rampart themed border',
  },
  {
    id: 13, name: 'ドラゴンパピー', rarity: 3, type: 'モンスター', emoji: '🐉',
    description: '卵から産まれたばかりの子ドラゴン。炎は小さくても愛嬌たっぷり。',
    skillName: 'ちびっこ炎ブレス',
    skillEffect: '全体に小ダメージ＋やけど効果。',
    promptTrait: 'an adorable baby dragon with tiny wings, round belly and puffing small flames happily',
    promptTheme: 'vivid red and golden scales tones, volcanic nest themed border',
  },
  {
    id: 14, name: '氷の精霊', rarity: 3, type: 'モンスター', emoji: '❄️',
    description: '凍てつく山に宿る氷の魂。怒ると周囲が吹雪になる。',
    skillName: '氷晶ストーム',
    skillEffect: '全体に中ダメージ＋スロー状態。',
    promptTrait: 'a beautiful translucent ice spirit with flowing crystal hair and icy blue aura',
    promptTheme: 'icy blue and crystalline white tones, frozen mountain peak themed border',
  },
  {
    id: 15, name: '聖騎士', rarity: 3, type: '冒険者', emoji: '⚜️',
    description: '神に誓いを立てた光の騎士。悪を倒すためなら命も惜しまない。',
    skillName: '聖なる断罪',
    skillEffect: '単体に大ダメージ。闇属性に特攻。',
    promptTrait: 'a radiant holy knight in gleaming white armor with a halo glow and raised holy sword',
    promptTheme: 'golden white and heavenly light tones, cathedral stained glass themed border',
  },
  {
    id: 16, name: '大魔法使い', rarity: 4, type: '冒険者', emoji: '🔮',
    description: '魔法学院の最高峰。あらゆる魔法を習得した伝説の学者。',
    skillName: '禁断の魔法陣',
    skillEffect: '全体に大ダメージ＋MP吸収。',
    promptTrait: 'an elegant elderly archmage in star-patterned robes with floating magical runes swirling around',
    promptTheme: 'deep violet and cosmic gold tones, ancient magic library themed border',
  },
  {
    id: 17, name: 'フェニックス', rarity: 4, type: 'モンスター', emoji: '🔥',
    description: '炎から何度でも蘇る不死の鳥。その炎は魂さえも燃やすという。',
    skillName: '不死の炎翼',
    skillEffect: '一度倒されても50%HPで復活。攻撃時全体炎ダメージ。',
    promptTrait: 'a majestic blazing phoenix spreading enormous fiery wings with trail of embers',
    promptTheme: 'brilliant crimson and molten gold tones, sky ablaze themed border',
  },
  {
    id: 18, name: 'ダークナイト', rarity: 4, type: '冒険者', emoji: '🌑',
    description: '光を捨てた元聖騎士。力を得た代わりに心を失った孤高の戦士。',
    skillName: '暗黒剣・魂斬り',
    skillEffect: '単体に超大ダメージ。自分も小ダメージを受ける。',
    promptTrait: 'a brooding dark knight in jet black armor with a cracked helmet revealing glowing red eyes',
    promptTheme: 'obsidian black and blood red tones, dark throne room themed border',
  },
  {
    id: 19, name: '伝説の勇者', rarity: 5, type: '冒険者', emoji: '👑',
    description: '世界を救った伝説の勇者。その名は時を越え今も語り継がれる。',
    skillName: '究極・英雄の剣',
    skillEffect: '全体に最大ダメージ＋全味方HP回復。',
    promptTrait: 'an epic golden hero radiating divine light, holding a legendary glowing sword aloft triumphantly',
    promptTheme: 'radiant gold and divine rainbow tones, legendary mountain peak themed border',
  },
  {
    id: 20, name: '魔王ゼロス', rarity: 5, type: 'モンスター', emoji: '😈',
    description: '闇を統べる魔王。その存在だけで世界が震える絶対的な支配者。',
    skillName: '絶滅の闇呪文',
    skillEffect: '全体に壊滅的ダメージ＋全デバフ付与。',
    promptTrait: 'an overwhelming demon lord with huge horns, floating in darkness surrounded by chaotic dark energy',
    promptTheme: 'absolute black and crimson void tones, shattered world throne themed border',
  },
];
